variable "ssm_key_name" {}
variable "govcloud_region" {}
variable "govcloud_access_key" {}
variable "govcloud_secret_key" {}
variable "spel_identifier" {}
variable "spel_builders" {}
variable "spel_extrapms" {}
variable "spel_ssm_access_key" {}
variable "spel_ssm_secret_key" {}
variable "commercial_aws_region" {}
