name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@1c7909107a55325d40d2f12f29029c73a38c45c3
    with:
      tardigradelint-target: install/pip_requirements/tests/requirements.txt lint
