name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@0a03f75193a010b3532cc90e8ad0b15a09ed33c1
    with:
      tardigradelint-target: install/pip_requirements/tests/requirements.txt lint
