name: Run lint and static analyis checks
on:
  pull_request:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: plus3it/actions-workflows/.github/workflows/lint.yml@a6e41877e630b2e3f15b265c2567cfb1076b1346
    with:
      tardigradelint-target: install/pip_requirements/tests/requirements.txt lint
